version: 2
default_settings: &default_settings
  docker:
    - image: circleci/node:12.16.3-stretch
  working_directory: ~/repo
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install-dependencies-and-lint
      - build:
          requires:
            - install-dependencies-and-lint
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
jobs:
  install-dependencies-and-lint:
    <<: *default_settings
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-
      - run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn typecheck
      - save_cache:
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  build:
    <<: *default_settings
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - public/
            - firebase.json
  deploy:
    <<: *default_settings
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: deploy to firebase
          command: npx firebase-tools deploy --only hosting --token $FIREBASE_DEPLOY_TOKEN --project $FIREBASE_PROJECT
